### ISSUE TITLE
error in recognizing the file containing the keywords

### ISSUE THREAD

**Issue by faizanmohiuddin482** [Satrat/Resume-Parser#4]

**Comment by faizanmohiuddin482** [comment]
Please type the name of a file containing all keywords associated with Computer Science separated by line
(leave blank for defaults)
python
Traceback (most recent call last):
  File "cvparseV2.py", line 428, in <module>
    (resume, cats) = init()
  File "cvparseV2.py", line 31, in init
    with open(path, "r") as fin:
IOError: [Errno 2] No such file or directory: 'python '
